# syntax=docker/dockerfile:1
#
# Official Phoenix release Dockerfile (generated by `mix phx.gen.release --docker`),
# customized for SQLite (ecto_sqlite3 / exqlite):
#   - sqlite3 CLI baked into the runtime image (for inspecting the database)
#   - /data volume dir for the SQLite database, writable by the `nobody` user
#   - tini as PID 1, and pending migrations run on boot before the server starts
#
# Base images (verified to exist on Docker Hub):
#   - docker.io/hexpm/elixir:1.20.2-erlang-29.0.2-debian-trixie-20260623-slim   (builder)
#   - docker.io/debian:trixie-20260623-slim                                     (runner)
ARG ELIXIR_VERSION=1.20.2
ARG OTP_VERSION=29.0.2
ARG DEBIAN_VERSION=trixie-20260623-slim

ARG BUILDER_IMAGE="docker.io/hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="docker.io/debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} AS builder

# install build dependencies
#   build-essential: gcc/make to compile exqlite's bundled SQLite C source
#   git:             the heroicons dep is fetched from GitHub
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential git \
  && rm -rf /var/lib/apt/lists/*

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force \
  && mix local.rebar --force

# set build ENV
ENV MIX_ENV="prod"

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

# copy compile-time config files before we compile dependencies
# to ensure any relevant config change will trigger the dependencies
# to be re-compiled.
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

# install esbuild + tailwind standalone binaries
RUN mix assets.setup

COPY priv priv

COPY lib lib

# Compile the release
RUN mix compile

COPY assets assets

# compile + digest assets (-> priv/static + cache_manifest.json)
RUN mix assets.deploy

# Changes to config/runtime.exs don't require recompiling the code
COPY config/runtime.exs config/

COPY rel rel
RUN mix release

# start a new build stage so that the final image will only contain
# the compiled release and other runtime necessities
FROM ${RUNNER_IMAGE} AS final

# runtime deps for the BEAM + exqlite NIF + outbound TLS, plus:
#   sqlite3: the SQLite CLI, baked in for inspecting the database
#   tini:    minimal init that reaps zombie processes (runs as PID 1)
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
       libstdc++6 openssl libncurses6 locales ca-certificates sqlite3 tini \
  && rm -rf /var/lib/apt/lists/*

# Set the locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
  && locale-gen

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# set runner ENV
ENV MIX_ENV="prod"

# The SQLite database lives on a mounted volume at /data. The default path is
# baked in here; docker-compose also sets DATABASE_PATH explicitly.
ENV DATABASE_PATH=/data/backs_backs_backs_prod.db
RUN mkdir -p /data && chown nobody /data

WORKDIR "/app"
RUN chown nobody /app

# Only copy the final release from the build stage
COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/backs_backs_backs ./

USER nobody

# /data is a named volume in docker-compose; declaring it documents the contract.
VOLUME /data
EXPOSE 4000

# Run pending migrations (creates the SQLite file + schema on first boot, and is
# idempotent thereafter), then start the Phoenix server. tini reaps zombies.
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/bin/sh", "-c", "/app/bin/migrate && exec /app/bin/server"]
