import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :backs_backs_backs, BacksBacksBacksWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# TLS is terminated by an upstream reverse proxy before requests reach Phoenix,
# so we deliberately do NOT force SSL or set HSTS here. The proxy handles HTTPS;
# forcing SSL inside the app would cause redirect loops behind the proxy.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
